using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;
using Alias_rifegrt_unitBuildData = D_unitBuildData;
using Alias_rifegrt_statDatas = D_statDatas;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class D_TileShpeData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new D_TileShpeData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new D_TileShpeData(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "TileShpeData";
		public const string name = "name";
		public const string unitBuildData = "unitBuildData";
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5526519764914468050UL,4239600642928235181UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public List<D_unitBuildData> f_unitBuildData => BGCodeGenUtils.GetNested<D_unitBuildData>(_f_unitBuildData, Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4612699089538755472UL, 15389567449175696803UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_unitBuildData;
	public static BansheeGz.BGDatabase.BGFieldNested _f_unitBuildData => _ufle12jhs77_f_unitBuildData ?? (_ufle12jhs77_f_unitBuildData = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5267104093635224925UL, 11893930471853365640UL), () => _ufle12jhs77_f_unitBuildData = null));
	private static readonly D_TileShpeData.Factory _factory0_PFS = new D_TileShpeData.Factory();
	private static readonly D_LocalUserData.Factory _factory1_PFS = new D_LocalUserData.Factory();
	private static readonly D_BoostDeck.Factory _factory2_PFS = new D_BoostDeck.Factory();
	private static readonly D_UnitData.Factory _factory3_PFS = new D_UnitData.Factory();
	private static readonly D_UnitStat.Factory _factory4_PFS = new D_UnitStat.Factory();
	private static readonly D_statDatas.Factory _factory5_PFS = new D_statDatas.Factory();
	private static readonly D_unitBuildData.Factory _factory6_PFS = new D_unitBuildData.Factory();
	private D_TileShpeData() : base(MetaDefault) {}
	private D_TileShpeData(BGId id) : base(MetaDefault, id) {}
	private D_TileShpeData(BGMetaEntity meta) : base(meta) {}
	private D_TileShpeData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static D_TileShpeData FindEntity(Predicate<D_TileShpeData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<D_TileShpeData> FindEntities(Predicate<D_TileShpeData> filter, List<D_TileShpeData> result=null, Comparison<D_TileShpeData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<D_TileShpeData> action, Predicate<D_TileShpeData> filter=null, Comparison<D_TileShpeData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static D_TileShpeData GetEntity(BGId entityId) => (D_TileShpeData) MetaDefault.GetEntity(entityId);
	public static D_TileShpeData GetEntity(int index) => (D_TileShpeData) MetaDefault[index];
	public static D_TileShpeData GetEntity(string entityName) => (D_TileShpeData) MetaDefault.GetEntity(entityName);
	public static D_TileShpeData NewEntity() => (D_TileShpeData) MetaDefault.NewEntity();
	public static D_TileShpeData NewEntity(BGId entityId) => (D_TileShpeData) MetaDefault.NewEntity(entityId);
	public static D_TileShpeData NewEntity(Action<D_TileShpeData> callback) => (D_TileShpeData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((D_TileShpeData)entity)));
}

public partial class D_LocalUserData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new D_LocalUserData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new D_LocalUserData(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "LocalUserData";
		public const string name = "name";
		public const string Gold = "Gold";
		public const string BoostDeck = "BoostDeck";
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4625932937206405802UL,11707112876743021752UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public System.Int32 f_Gold
	{
		get => _f_Gold[Index];
		set => _f_Gold[Index] = value;
	}
	public List<D_BoostDeck> f_BoostDeck => BGCodeGenUtils.GetNested<D_BoostDeck>(_f_BoostDeck, Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5570864947923372496UL, 16114093359231942036UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Gold;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Gold => _ufle12jhs77_f_Gold ?? (_ufle12jhs77_f_Gold = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4683257009118535675UL, 10952020009379038888UL), () => _ufle12jhs77_f_Gold = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_BoostDeck;
	public static BansheeGz.BGDatabase.BGFieldNested _f_BoostDeck => _ufle12jhs77_f_BoostDeck ?? (_ufle12jhs77_f_BoostDeck = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5417050161172596524UL, 5519351679311806344UL), () => _ufle12jhs77_f_BoostDeck = null));
	private static readonly D_TileShpeData.Factory _factory0_PFS = new D_TileShpeData.Factory();
	private static readonly D_LocalUserData.Factory _factory1_PFS = new D_LocalUserData.Factory();
	private static readonly D_BoostDeck.Factory _factory2_PFS = new D_BoostDeck.Factory();
	private static readonly D_UnitData.Factory _factory3_PFS = new D_UnitData.Factory();
	private static readonly D_UnitStat.Factory _factory4_PFS = new D_UnitStat.Factory();
	private static readonly D_statDatas.Factory _factory5_PFS = new D_statDatas.Factory();
	private static readonly D_unitBuildData.Factory _factory6_PFS = new D_unitBuildData.Factory();
	private D_LocalUserData() : base(MetaDefault) {}
	private D_LocalUserData(BGId id) : base(MetaDefault, id) {}
	private D_LocalUserData(BGMetaEntity meta) : base(meta) {}
	private D_LocalUserData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static D_LocalUserData FindEntity(Predicate<D_LocalUserData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<D_LocalUserData> FindEntities(Predicate<D_LocalUserData> filter, List<D_LocalUserData> result=null, Comparison<D_LocalUserData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<D_LocalUserData> action, Predicate<D_LocalUserData> filter=null, Comparison<D_LocalUserData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static D_LocalUserData GetEntity(BGId entityId) => (D_LocalUserData) MetaDefault.GetEntity(entityId);
	public static D_LocalUserData GetEntity(int index) => (D_LocalUserData) MetaDefault[index];
	public static D_LocalUserData GetEntity(string entityName) => (D_LocalUserData) MetaDefault.GetEntity(entityName);
	public static D_LocalUserData NewEntity() => (D_LocalUserData) MetaDefault.NewEntity();
	public static D_LocalUserData NewEntity(BGId entityId) => (D_LocalUserData) MetaDefault.NewEntity(entityId);
	public static D_LocalUserData NewEntity(Action<D_LocalUserData> callback) => (D_LocalUserData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((D_LocalUserData)entity)));
}

public partial class D_BoostDeck : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new D_BoostDeck(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new D_BoostDeck(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "BoostDeck";
		public const string name = "name";
		public const string LocalUserData = "LocalUserData";
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5516462181609044315UL,3959596604375669897UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public D_LocalUserData f_LocalUserData
	{
		get => (D_LocalUserData) _f_LocalUserData[Index];
		set => _f_LocalUserData[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5197673912409473507UL, 13854933137346017459UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_LocalUserData;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_LocalUserData => _ufle12jhs77_f_LocalUserData ?? (_ufle12jhs77_f_LocalUserData = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5157762030127206670UL, 18423548300425324437UL), () => _ufle12jhs77_f_LocalUserData = null));
	private static readonly D_TileShpeData.Factory _factory0_PFS = new D_TileShpeData.Factory();
	private static readonly D_LocalUserData.Factory _factory1_PFS = new D_LocalUserData.Factory();
	private static readonly D_BoostDeck.Factory _factory2_PFS = new D_BoostDeck.Factory();
	private static readonly D_UnitData.Factory _factory3_PFS = new D_UnitData.Factory();
	private static readonly D_UnitStat.Factory _factory4_PFS = new D_UnitStat.Factory();
	private static readonly D_statDatas.Factory _factory5_PFS = new D_statDatas.Factory();
	private static readonly D_unitBuildData.Factory _factory6_PFS = new D_unitBuildData.Factory();
	private D_BoostDeck() : base(MetaDefault) {}
	private D_BoostDeck(BGId id) : base(MetaDefault, id) {}
	private D_BoostDeck(BGMetaEntity meta) : base(meta) {}
	private D_BoostDeck(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static D_BoostDeck FindEntity(Predicate<D_BoostDeck> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<D_BoostDeck> FindEntities(Predicate<D_BoostDeck> filter, List<D_BoostDeck> result=null, Comparison<D_BoostDeck> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<D_BoostDeck> action, Predicate<D_BoostDeck> filter=null, Comparison<D_BoostDeck> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static D_BoostDeck GetEntity(BGId entityId) => (D_BoostDeck) MetaDefault.GetEntity(entityId);
	public static D_BoostDeck GetEntity(int index) => (D_BoostDeck) MetaDefault[index];
	public static D_BoostDeck GetEntity(string entityName) => (D_BoostDeck) MetaDefault.GetEntity(entityName);
	public static D_BoostDeck NewEntity() => (D_BoostDeck) MetaDefault.NewEntity();
	public static D_BoostDeck NewEntity(BGId entityId) => (D_BoostDeck) MetaDefault.NewEntity(entityId);
	public static D_BoostDeck NewEntity(Action<D_BoostDeck> callback) => (D_BoostDeck) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((D_BoostDeck)entity)));
	public static D_BoostDeck NewEntity(D_LocalUserData owner) => (D_BoostDeck) MetaDefault.NewEntity(owner);
	public static D_BoostDeck NewEntity(D_LocalUserData owner, BGId entityId) => (D_BoostDeck) MetaDefault.NewEntity(owner, entityId);
	public static D_BoostDeck NewEntity(D_LocalUserData owner, Action<D_BoostDeck> callback) => (D_BoostDeck) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((D_BoostDeck)entity)));
}

public partial class D_UnitData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new D_UnitData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new D_UnitData(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "UnitData";
		public const string name = "name";
		public const string statDatas = "statDatas";
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5098187849243670608UL,7590059858118427043UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public List<D_statDatas> f_statDatas => BGCodeGenUtils.GetNested<D_statDatas>(_f_statDatas, Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4978381386621882592UL, 9377071611302703509UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_statDatas;
	public static BansheeGz.BGDatabase.BGFieldNested _f_statDatas => _ufle12jhs77_f_statDatas ?? (_ufle12jhs77_f_statDatas = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5475734705730849580UL, 3233909037450398366UL), () => _ufle12jhs77_f_statDatas = null));
	public List<Alias_rifegrt_unitBuildData> RelatedunitBuildDataListUsingunitDataRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_unitBuildData>(Alias_rifegrt_unitBuildData._f_unitData, Id);
	private static readonly D_TileShpeData.Factory _factory0_PFS = new D_TileShpeData.Factory();
	private static readonly D_LocalUserData.Factory _factory1_PFS = new D_LocalUserData.Factory();
	private static readonly D_BoostDeck.Factory _factory2_PFS = new D_BoostDeck.Factory();
	private static readonly D_UnitData.Factory _factory3_PFS = new D_UnitData.Factory();
	private static readonly D_UnitStat.Factory _factory4_PFS = new D_UnitStat.Factory();
	private static readonly D_statDatas.Factory _factory5_PFS = new D_statDatas.Factory();
	private static readonly D_unitBuildData.Factory _factory6_PFS = new D_unitBuildData.Factory();
	private D_UnitData() : base(MetaDefault) {}
	private D_UnitData(BGId id) : base(MetaDefault, id) {}
	private D_UnitData(BGMetaEntity meta) : base(meta) {}
	private D_UnitData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static D_UnitData FindEntity(Predicate<D_UnitData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<D_UnitData> FindEntities(Predicate<D_UnitData> filter, List<D_UnitData> result=null, Comparison<D_UnitData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<D_UnitData> action, Predicate<D_UnitData> filter=null, Comparison<D_UnitData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static D_UnitData GetEntity(BGId entityId) => (D_UnitData) MetaDefault.GetEntity(entityId);
	public static D_UnitData GetEntity(int index) => (D_UnitData) MetaDefault[index];
	public static D_UnitData GetEntity(string entityName) => (D_UnitData) MetaDefault.GetEntity(entityName);
	public static D_UnitData NewEntity() => (D_UnitData) MetaDefault.NewEntity();
	public static D_UnitData NewEntity(BGId entityId) => (D_UnitData) MetaDefault.NewEntity(entityId);
	public static D_UnitData NewEntity(Action<D_UnitData> callback) => (D_UnitData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((D_UnitData)entity)));
}

public partial class D_UnitStat : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new D_UnitStat(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new D_UnitStat(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "UnitStat";
		public const string name = "name";
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5186153289177203967UL,17808808904195242630UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5161906705463305257UL, 6833134698217662355UL), () => _ufle12jhs77_f_name = null));
	public List<Alias_rifegrt_statDatas> RelatedstatDatasListUsingstatRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_statDatas>(Alias_rifegrt_statDatas._f_stat, Id);
	private static readonly D_TileShpeData.Factory _factory0_PFS = new D_TileShpeData.Factory();
	private static readonly D_LocalUserData.Factory _factory1_PFS = new D_LocalUserData.Factory();
	private static readonly D_BoostDeck.Factory _factory2_PFS = new D_BoostDeck.Factory();
	private static readonly D_UnitData.Factory _factory3_PFS = new D_UnitData.Factory();
	private static readonly D_UnitStat.Factory _factory4_PFS = new D_UnitStat.Factory();
	private static readonly D_statDatas.Factory _factory5_PFS = new D_statDatas.Factory();
	private static readonly D_unitBuildData.Factory _factory6_PFS = new D_unitBuildData.Factory();
	private D_UnitStat() : base(MetaDefault) {}
	private D_UnitStat(BGId id) : base(MetaDefault, id) {}
	private D_UnitStat(BGMetaEntity meta) : base(meta) {}
	private D_UnitStat(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static D_UnitStat FindEntity(Predicate<D_UnitStat> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<D_UnitStat> FindEntities(Predicate<D_UnitStat> filter, List<D_UnitStat> result=null, Comparison<D_UnitStat> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<D_UnitStat> action, Predicate<D_UnitStat> filter=null, Comparison<D_UnitStat> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static D_UnitStat GetEntity(BGId entityId) => (D_UnitStat) MetaDefault.GetEntity(entityId);
	public static D_UnitStat GetEntity(int index) => (D_UnitStat) MetaDefault[index];
	public static D_UnitStat GetEntity(string entityName) => (D_UnitStat) MetaDefault.GetEntity(entityName);
	public static D_UnitStat NewEntity() => (D_UnitStat) MetaDefault.NewEntity();
	public static D_UnitStat NewEntity(BGId entityId) => (D_UnitStat) MetaDefault.NewEntity(entityId);
	public static D_UnitStat NewEntity(Action<D_UnitStat> callback) => (D_UnitStat) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((D_UnitStat)entity)));
}

public partial class D_statDatas : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new D_statDatas(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new D_statDatas(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "statDatas";
		public const string name = "name";
		public const string UnitData = "UnitData";
		public const string stat = "stat";
		public const string value = "value";
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4677001862833252198UL,17227539508812832132UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public D_UnitData f_UnitData
	{
		get => (D_UnitData) _f_UnitData[Index];
		set => _f_UnitData[Index] = value;
	}
	public D_UnitStat f_stat
	{
		get => (D_UnitStat) _f_stat[Index];
		set => _f_stat[Index] = value;
	}
	public System.Int32 f_value
	{
		get => _f_value[Index];
		set => _f_value[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5240328156132197605UL, 8112268647951590819UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_UnitData;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_UnitData => _ufle12jhs77_f_UnitData ?? (_ufle12jhs77_f_UnitData = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5313188107870138402UL, 5719261033964088505UL), () => _ufle12jhs77_f_UnitData = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_stat;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_stat => _ufle12jhs77_f_stat ?? (_ufle12jhs77_f_stat = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5256411640760305846UL, 3061902281380513942UL), () => _ufle12jhs77_f_stat = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_value;
	public static BansheeGz.BGDatabase.BGFieldInt _f_value => _ufle12jhs77_f_value ?? (_ufle12jhs77_f_value = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5427435841711547707UL, 17735938886241975448UL), () => _ufle12jhs77_f_value = null));
	private static readonly D_TileShpeData.Factory _factory0_PFS = new D_TileShpeData.Factory();
	private static readonly D_LocalUserData.Factory _factory1_PFS = new D_LocalUserData.Factory();
	private static readonly D_BoostDeck.Factory _factory2_PFS = new D_BoostDeck.Factory();
	private static readonly D_UnitData.Factory _factory3_PFS = new D_UnitData.Factory();
	private static readonly D_UnitStat.Factory _factory4_PFS = new D_UnitStat.Factory();
	private static readonly D_statDatas.Factory _factory5_PFS = new D_statDatas.Factory();
	private static readonly D_unitBuildData.Factory _factory6_PFS = new D_unitBuildData.Factory();
	private D_statDatas() : base(MetaDefault) {}
	private D_statDatas(BGId id) : base(MetaDefault, id) {}
	private D_statDatas(BGMetaEntity meta) : base(meta) {}
	private D_statDatas(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static D_statDatas FindEntity(Predicate<D_statDatas> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<D_statDatas> FindEntities(Predicate<D_statDatas> filter, List<D_statDatas> result=null, Comparison<D_statDatas> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<D_statDatas> action, Predicate<D_statDatas> filter=null, Comparison<D_statDatas> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static D_statDatas GetEntity(BGId entityId) => (D_statDatas) MetaDefault.GetEntity(entityId);
	public static D_statDatas GetEntity(int index) => (D_statDatas) MetaDefault[index];
	public static D_statDatas GetEntity(string entityName) => (D_statDatas) MetaDefault.GetEntity(entityName);
	public static D_statDatas NewEntity() => (D_statDatas) MetaDefault.NewEntity();
	public static D_statDatas NewEntity(BGId entityId) => (D_statDatas) MetaDefault.NewEntity(entityId);
	public static D_statDatas NewEntity(Action<D_statDatas> callback) => (D_statDatas) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((D_statDatas)entity)));
	public static D_statDatas NewEntity(D_UnitData owner) => (D_statDatas) MetaDefault.NewEntity(owner);
	public static D_statDatas NewEntity(D_UnitData owner, BGId entityId) => (D_statDatas) MetaDefault.NewEntity(owner, entityId);
	public static D_statDatas NewEntity(D_UnitData owner, Action<D_statDatas> callback) => (D_statDatas) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((D_statDatas)entity)));
}

public partial class D_unitBuildData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new D_unitBuildData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new D_unitBuildData(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "unitBuildData";
		public const string name = "name";
		public const string TileShpeData = "TileShpeData";
		public const string unitData = "unitData";
		public const string position = "position";
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4799327628856687378UL,3776090101215706293UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String f_name
	{
		get => _f_name[Index];
		set => _f_name[Index] = value;
	}
	public D_TileShpeData f_TileShpeData
	{
		get => (D_TileShpeData) _f_TileShpeData[Index];
		set => _f_TileShpeData[Index] = value;
	}
	public D_UnitData f_unitData
	{
		get => (D_UnitData) _f_unitData[Index];
		set => _f_unitData[Index] = value;
	}
	public UnityEngine.Vector2 f_position
	{
		get => _f_position[Index];
		set => _f_position[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5119949781748048341UL, 1974210095801998015UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_TileShpeData;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_TileShpeData => _ufle12jhs77_f_TileShpeData ?? (_ufle12jhs77_f_TileShpeData = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5201128059908877541UL, 10865111936391984023UL), () => _ufle12jhs77_f_TileShpeData = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_unitData;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_unitData => _ufle12jhs77_f_unitData ?? (_ufle12jhs77_f_unitData = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4832644335004946023UL, 16677909979451640761UL), () => _ufle12jhs77_f_unitData = null));
	private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_f_position;
	public static BansheeGz.BGDatabase.BGFieldVector2 _f_position => _ufle12jhs77_f_position ?? (_ufle12jhs77_f_position = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldVector2>(MetaDefault, new BGId(4996388341754236581UL, 9961606815976867004UL), () => _ufle12jhs77_f_position = null));
	private static readonly D_TileShpeData.Factory _factory0_PFS = new D_TileShpeData.Factory();
	private static readonly D_LocalUserData.Factory _factory1_PFS = new D_LocalUserData.Factory();
	private static readonly D_BoostDeck.Factory _factory2_PFS = new D_BoostDeck.Factory();
	private static readonly D_UnitData.Factory _factory3_PFS = new D_UnitData.Factory();
	private static readonly D_UnitStat.Factory _factory4_PFS = new D_UnitStat.Factory();
	private static readonly D_statDatas.Factory _factory5_PFS = new D_statDatas.Factory();
	private static readonly D_unitBuildData.Factory _factory6_PFS = new D_unitBuildData.Factory();
	private D_unitBuildData() : base(MetaDefault) {}
	private D_unitBuildData(BGId id) : base(MetaDefault, id) {}
	private D_unitBuildData(BGMetaEntity meta) : base(meta) {}
	private D_unitBuildData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static D_unitBuildData FindEntity(Predicate<D_unitBuildData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<D_unitBuildData> FindEntities(Predicate<D_unitBuildData> filter, List<D_unitBuildData> result=null, Comparison<D_unitBuildData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<D_unitBuildData> action, Predicate<D_unitBuildData> filter=null, Comparison<D_unitBuildData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static D_unitBuildData GetEntity(BGId entityId) => (D_unitBuildData) MetaDefault.GetEntity(entityId);
	public static D_unitBuildData GetEntity(int index) => (D_unitBuildData) MetaDefault[index];
	public static D_unitBuildData GetEntity(string entityName) => (D_unitBuildData) MetaDefault.GetEntity(entityName);
	public static D_unitBuildData NewEntity() => (D_unitBuildData) MetaDefault.NewEntity();
	public static D_unitBuildData NewEntity(BGId entityId) => (D_unitBuildData) MetaDefault.NewEntity(entityId);
	public static D_unitBuildData NewEntity(Action<D_unitBuildData> callback) => (D_unitBuildData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((D_unitBuildData)entity)));
	public static D_unitBuildData NewEntity(D_TileShpeData owner) => (D_unitBuildData) MetaDefault.NewEntity(owner);
	public static D_unitBuildData NewEntity(D_TileShpeData owner, BGId entityId) => (D_unitBuildData) MetaDefault.NewEntity(owner, entityId);
	public static D_unitBuildData NewEntity(D_TileShpeData owner, Action<D_unitBuildData> callback) => (D_unitBuildData) MetaDefault.NewEntity(owner, new BGMetaEntity.NewEntityContext(entity => callback((D_unitBuildData)entity)));
}
#pragma warning restore 414
